config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    sessions: 'users/sessions',
    registrations: 'users/registrations' 
  }

  root to: "searches/request#index"

  namespace :searches do
    resources :request
  end

  namespace :articles do
    resources :post
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :codes
  has_many :urls
  has_many :comments
  acts_as_taggable

  validates :title, presence: true
  validates :solution, presence: true
  validates :user_id, presence: true
end

app/models/code.rb
class Code < ApplicationRecord
  belongs_to :article
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :article
end

app/models/url.rb
class Url < ApplicationRecord
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
  has_many :comments
  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/articles/post_controller.rb
class Articles::PostController < ApplicationController
  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to root_path
    else
      @errors = "こちらは必須事項です！"
      render "new"
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  private
  def article_params
    params.require("article").permit(:title, :solution, :factor, :knowledge, :tag_list).merge(user_id: current_user.id)
  end

end

app/controllers/searches/request_controller.rb
class Searches::RequestController < ApplicationController
  def index
    @articles = Article.all
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles/post_helper.rb
module Articles::PostHelper
end

app/views/articles/post/new.html.erb
<%= form_for @article, url: {controller: "post", action: "create" } do |f| %>
  <div class="title">
    <%= f.label :title %>
    <%= f.text_field :title %>  
    <% if @article.errors.messages[:title] != [] %>
      <div class="warning_message">
        <%= @errors %>
      </div>
    <% end %>
  </div>
  <div class="tags">
    <%= f.label :tag_list %>
    <%= text_field_tag 'article[tag_list]', @article.tag_list.join(","), data: {role: "tagsinput"} %>
  </div>
  <div class="solution">
    <%= f.label :solution %>
    <%= f.text_field :solution %>
    <% if @article.errors.messages[:solution] != [] %>
      <div class="warning_message">
        <%= @errors %>
      </div>
    <% end %>
  </div>
  <div class="factor">
    <%= f.label :factor %>
    <%= f.text_field :factor %>
  </div>
  <div class="knowledge">
    <%= f.label :knowledge %>
    <%= f.text_field :knowledge %> 
  </div>
  <%= f.submit "送信する" %>  
<% end %>

app/views/articles/post/show.html.erb
<%= render "shared/header" %>
<div class="top_wrapper">
  <div class="article">
    <div class="article__title">
      <%= "タイトル: #{@article.title}" %>
    </div>
    <div class="article__solution">
      <%= "解決方法:#{@article.solution}" %>
    </div>
    <div class="article__solution">
      <%= "原因:#{@article.factor}" %>
    </div>
    <div class="article__solution">
      <%= "学習したこと:#{@article.knowledge}" %>
    </div>
    <div class="article__box">
      <%= link_to "詳細はクリック！", articles_post_path(@article.id) %>
    </div>
  </div>
  <%= render "shared/side_bar" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechFaq</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/searches/request/index.html.erb
<%= render "shared/header" %>
<div class="wrapper">
  <%= render "shared/main" %>
  <%= render "shared/side_bar" %>
</div>

app/views/shared/_article.html.erb
  <div class="article">
    <div class="article__title">
      <%= "タイトル: #{article.title}" %>
    </div>
    <div class="article__tags">
      <div class="article__tags__label">
        タグ:
      </div>
      <div class="article__tags__box", data-role="tagsinput" >
        <% article.tag_list.each do |tag| %>
          <span class="badge badge-info">
            <%= tag %>
          </span>
        <% end %>
      </div>
    </div>
    <div class="article__solution">
      <%= "解決方法:#{article.solution}" %>
    </div>
    <div class="article__box">
      <%= link_to "詳細はクリック！", articles_post_path(article.id) %>
      <div class="hidden_detail">
        <div class="article__factor">
          <%= "要因:#{article.factor}" %>
        </div> 
        <div class="article__knowledge">
          <%= "学んだこと:#{article.knowledge}" %>
        </div> 
      </div>
    </div>
  </div>

app/views/shared/_header.html.erb
<header>
  <div class="header">
    <%= link_to "TECH::FAQ", root_path %>
    <div class="right_box">
      <ul class="list">
        <% if user_signed_in? %>
          <li class="list__box">
            <%= link_to "MYPAGE", "#" %>      
          </li>
          <li class="list__box">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>  
          </li> 
          <li class="list__box">
            <%= link_to "新規投稿", new_articles_post_path %>     
          </li>
          <li class="list__box">
            <%= link_to "編集", "#" %>    
          </li>
          <li class="list__box">
            <%= link_to "削除", "#" %>      
          </li>
        <% else %>
          <li class="list__box">
            <%= link_to "新規会員登録", new_user_registration_path %>     
          </li>
          <li class="list__box">
            <%= link_to "ログイン", new_user_session_path %>     
          </li> 
        <% end %>
      </ul>



     
 
         
    </div>
  </div>
</header>

app/views/shared/_main.html.erb
<div class="main">
  <div class="top_wrapper">
    <input type="text" placeholder="検索窓">
    <p>投稿一覧</p>
  </div>
  <div class="middle_wrapper">
    <div class="articles">
      <% @articles.each do |article| %>
        <%= render "shared/article", {article: article} %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_side_bar.html.erb
<div class="side_bar__box">
  <div class="side_bar__contents">
    <div class="side_bar__content">
      <div class="side_bar__content__mypage">
        <p class="side_bar__content__title">MyPage</p>
      </div>
    </div>
    <div class="side_bar__content">
      <div class="side_bar__content__progress">
        <p class="side_bar__content__title">学習進捗率</p>
      </div>
    </div>
    <div class="side_bar__content">
      <div class="side_bar__content__check">
        <p class="side_bar__content__title">理解度チェック</p>
      </div>
    </div>
  </div>

</div>